# Generated by Django 3.2.9 on 2021-11-14 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_type', models.CharField(choices=[('S', 'Stock'), ('B', 'Bitcoin')], max_length=1)),
                ('name_of_the_idea', models.CharField(max_length=255)),
                ('risk_category', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High')], max_length=1)),
                ('stoploss_at', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency_in', models.CharField(choices=[('IR', 'RUPEE'), ('AD', 'DOLLAR')], max_length=2)),
                ('book_profit_near', models.DecimalField(decimal_places=2, max_digits=15)),
                ('up_or_down_side_in_percent', models.DecimalField(decimal_places=2, max_digits=4)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_user', to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ManyToManyField(blank=True, null=True, related_name='ideas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
