# Generated by Django 3.2.9 on 2021-11-14 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='subscriber',
            field=models.ManyToManyField(blank=True, related_name='ideas', to=settings.AUTH_USER_MODEL),
        ),
    ]
